[package]
name = "edgedemo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.dev]
lto = true
opt-level = 'z'

[dependencies]
image= {version = "0.24.9",default-features = false, features = ["jpeg"]}